# Site settings
author: Chamila Dharmawardhana
title: Data Science begins
header-img: img/home-bg.png
email: ccdxz8@mail.umkc.edu
copyright_name: Chamila Dharmawardhana
description: > # this means to ignore newlines until "baseurl:"
  Flatiron bootcamp projects
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  GitHub-ccd

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
